import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { beforeEach, describe, expect, it } from 'vitest';
import { agentReportSchema } from '@sakuradrive/shared';
import { createTestContext, type TestContext } from './helpers.js';

/**
 * Cross-language contract test.
 *
 * The fixture is generated by the PowerShell agent's own parsing functions
 * (`agent/tools/New-ContractFixture.ps1`) from representative smartctl and dpcmd
 * output. Running it through the real ingest path is what proves the two halves of
 * the system still agree — a change to either side that breaks the contract fails
 * here rather than silently producing an agent that reports nothing.
 */
const fixturePath = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  'fixtures',
  'agent-report.json',
);
const fixture = JSON.parse(readFileSync(fixturePath, 'utf8')) as unknown;

let ctx: TestContext;

beforeEach(() => {
  ctx = createTestContext();
});

describe('agent report contract', () => {
  it('validates against the protocol schema', () => {
    const result = agentReportSchema.safeParse(fixture);
    if (!result.success) {
      throw new Error(`Agent fixture no longer matches the protocol:\n${result.error}`);
    }
    expect(result.data.hostname).toBe('NAS-01');
    expect(result.data.protocolVersion).toBe(1);
  });

  it('ingests cleanly, producing drives keyed by serial number', () => {
    ctx.agents.ingest(agentReportSchema.parse(fixture));
    const drives = ctx.agents.listDrives();
    expect(drives).toHaveLength(3);
    expect(drives.map((drive) => drive.deviceKey).sort()).toEqual([
      'sn:S6Z1NJ0T900001',
      'sn:WD-ABC123',
      'sn:WD-DEF456',
    ]);
  });

  it('attaches the volume labels the operator reads off the caddies', () => {
    ctx.agents.ingest(agentReportSchema.parse(fixture));
    const drive = ctx.agents.listDrives().find((candidate) => candidate.serialNumber === 'WD-ABC123')!;
    expect(drive.labels).toEqual(['DRIVEPOOL27']);
    expect(drive.driveLetters).toEqual(['E']);
    expect(drive.poolNames).toEqual(['HDD Pool']);
  });

  it('records the pool and both of its parts', () => {
    ctx.agents.ingest(agentReportSchema.parse(fixture));
    const pools = ctx.agents.listPools();
    expect(pools).toHaveLength(1);
    expect(pools[0]!.name).toBe('HDD Pool');
    expect(pools[0]!.parts.map((part) => part.volumeLabel).sort()).toEqual([
      'DRIVEPOOL27',
      'DRIVEPOOL28',
    ]);
    expect(pools[0]!.parts[0]!.deviceKey).toMatch(/^sn:/);
  });

  it('imports the duplication rules dpcmd reported, minus redundant ones', () => {
    ctx.agents.ingest(agentReportSchema.parse(fixture));
    const rules = ctx.settings.get().duplication.rules;
    expect(rules.map((rule) => rule.path).sort()).toEqual(['', 'Backups', 'Media', 'Media/Movies/4K']);
    expect(rules.find((rule) => rule.path === 'Media/Movies/4K')!.level).toBe(3);
    expect(rules.every((rule) => rule.source === 'drivepool')).toBe(true);
  });

  it('raises the alerts the reported data warrants and no others', () => {
    ctx.agents.ingest(agentReportSchema.parse(fixture));
    const alerts = ctx.alerts.list().alerts;
    const keys = alerts.map((alert) => alert.dedupeKey).sort();

    // Two pending sectors on DRIVEPOOL27, a dirty bit and almost no free space on
    // DRIVEPOOL28 — everything else in the fixture is healthy.
    expect(keys).toContain('smart:sn:WD-ABC123:smart.attr.197');
    expect(
      alerts.find((alert) => alert.dedupeKey === 'smart:sn:WD-ABC123:smart.attr.197')!.title,
    ).toContain('DRIVEPOOL27');
    expect(keys.some((key) => key.endsWith(':volume.dirty'))).toBe(true);
    expect(keys.some((key) => key.endsWith(':volume.free-space'))).toBe(true);
    expect(keys.some((key) => key.startsWith('nvme.'))).toBe(false);
  });

  it('parses the NVMe health log into wear and spare figures', () => {
    ctx.agents.ingest(agentReportSchema.parse(fixture));
    const drive = ctx.agents.listDrives().find((candidate) => candidate.mediaType === 'SSD')!;
    const detail = ctx.agents.driveDetail(drive.id);
    expect(detail.latestSmart!.nvme).toMatchObject({
      percentageUsed: 7,
      availableSpare: 100,
      unsafeShutdowns: 11,
    });
    // 316 K, converted to Celsius by the agent.
    expect(detail.latestSmart!.temperatureC).toBe(43);
  });

  it('stores the performance samples and flags the slow disk after three reports', () => {
    const report = agentReportSchema.parse(fixture);
    ctx.agents.ingest(report);
    ctx.agents.ingest(report);
    ctx.agents.ingest(report);

    const perfAlerts = ctx.alerts.list().alerts.filter((alert) => alert.category === 'performance');
    expect(perfAlerts.length).toBeGreaterThan(0);
    // The fixture's second disk sits at 912ms read latency with a queue of 44.
    expect(perfAlerts.some((alert) => alert.title.includes('DRIVEPOOL28'))).toBe(true);
    expect(perfAlerts.every((alert) => alert.severity === 'critical')).toBe(true);
  });

  it('records why PrimoCache statistics are missing rather than staying silent', () => {
    const result = ctx.agents.ingest(agentReportSchema.parse(fixture));
    expect(result.warnings).toContain('primocache: No command line interface found');
    const latest = ctx.agents.latestPrimoCache()!;
    expect(latest.available).toBe(false);
    expect((latest.data as { reason: string }).reason).toContain('no command line interface');
  });

  it('is idempotent: re-posting the same report changes nothing', () => {
    ctx.agents.ingest(agentReportSchema.parse(fixture));
    const first = ctx.alerts.list().total;
    ctx.agents.ingest(agentReportSchema.parse(fixture));
    expect(ctx.agents.listDrives()).toHaveLength(3);
    expect(ctx.agents.listPools()[0]!.parts).toHaveLength(2);
    expect(ctx.alerts.list().total).toBe(first);
  });
});
